apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rsenvcomp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rsenvcomp
    app.kubernetes.io/part-of: rsenvapp
  name: rsenvcomp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: rsenvcomp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: rsenvcomp
    spec:
      containers:
      - image: quay.io/abarbaro-org/rs-demos-vlqh-tenant/rsenvapp/rsenvcomp@sha256:8ba0d52204c617e0b33dda05d533ed6cb00c04291f78990701cd0b99f4ea197a
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
